"""Update UploadedDocument schema

Revision ID: 2fdf09e3e6b6
Revises: a86c0a333fed
Create Date: 2026-05-26 20:02:01.915711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdf09e3e6b6'
down_revision: Union[str, Sequence[str], None] = 'a86c0a333fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('uploaded_documents', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('uploaded_documents', sa.Column('subject_id', sa.String(), nullable=False))
    op.add_column('uploaded_documents', sa.Column('student_id', sa.String(), nullable=False))
    op.drop_column('uploaded_documents', 'file_url')
    op.drop_column('uploaded_documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_documents', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('uploaded_documents', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('uploaded_documents', 'student_id')
    op.drop_column('uploaded_documents', 'subject_id')
    op.drop_column('uploaded_documents', 'content_type')
    op.drop_column('uploaded_documents', 'file_path')
    # ### end Alembic commands ###
