"""Add quiz_id to QuizAttempt

Revision ID: 9931788c0058
Revises: 2fdf09e3e6b6
Create Date: 2026-05-26 23:21:39.697989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9931788c0058'
down_revision: Union[str, Sequence[str], None] = '2fdf09e3e6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('quiz_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'quiz_id')
    # ### end Alembic commands ###
