"""Add student_id to Subject

Revision ID: a86c0a333fed
Revises: 93f33ea0cc27
Create Date: 2026-05-26 19:53:40.376928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86c0a333fed'
down_revision: Union[str, Sequence[str], None] = '93f33ea0cc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('student_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'student_id')
    # ### end Alembic commands ###
