"""Remove users FK

Revision ID: e1aac765c2bd
Revises: 9931788c0058
Create Date: 2026-05-26 23:49:14.687089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1aac765c2bd'
down_revision: Union[str, Sequence[str], None] = '9931788c0058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_feedback_logs_user_id_fkey'), 'ai_feedback_logs', type_='foreignkey')
    op.drop_constraint(op.f('learning_sessions_user_id_fkey'), 'learning_sessions', type_='foreignkey')
    op.drop_constraint(op.f('mastery_tracking_user_id_fkey'), 'mastery_tracking', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('weaknesses_user_id_fkey'), 'weaknesses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('weaknesses_user_id_fkey'), 'weaknesses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('mastery_tracking_user_id_fkey'), 'mastery_tracking', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('learning_sessions_user_id_fkey'), 'learning_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('ai_feedback_logs_user_id_fkey'), 'ai_feedback_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
